// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: credentials.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCredential = `-- name: CreateCredential :one
INSERT INTO credentials (
    id, user_id, public_key, transport,
    sign_count, flag_backup_eligible, flag_backup_state, aaguid
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, public_key, transport, sign_count, flag_backup_eligible, flag_backup_state, aaguid, created_at
`

type CreateCredentialParams struct {
	ID                 []byte      `json:"id"`
	UserID             pgtype.UUID `json:"user_id"`
	PublicKey          []byte      `json:"public_key"`
	Transport          []string    `json:"transport"`
	SignCount          int64       `json:"sign_count"`
	FlagBackupEligible bool        `json:"flag_backup_eligible"`
	FlagBackupState    bool        `json:"flag_backup_state"`
	Aaguid             []byte      `json:"aaguid"`
}

func (q *Queries) CreateCredential(ctx context.Context, arg CreateCredentialParams) (Credential, error) {
	row := q.db.QueryRow(ctx, createCredential,
		arg.ID,
		arg.UserID,
		arg.PublicKey,
		arg.Transport,
		arg.SignCount,
		arg.FlagBackupEligible,
		arg.FlagBackupState,
		arg.Aaguid,
	)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PublicKey,
		&i.Transport,
		&i.SignCount,
		&i.FlagBackupEligible,
		&i.FlagBackupState,
		&i.Aaguid,
		&i.CreatedAt,
	)
	return i, err
}

const getCredentialsByUserID = `-- name: GetCredentialsByUserID :many
SELECT id, user_id, public_key, transport, sign_count, flag_backup_eligible, flag_backup_state, aaguid, created_at FROM credentials WHERE user_id = $1
`

func (q *Queries) GetCredentialsByUserID(ctx context.Context, userID pgtype.UUID) ([]Credential, error) {
	rows, err := q.db.Query(ctx, getCredentialsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Credential{}
	for rows.Next() {
		var i Credential
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PublicKey,
			&i.Transport,
			&i.SignCount,
			&i.FlagBackupEligible,
			&i.FlagBackupState,
			&i.Aaguid,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCredentialAfterLogin = `-- name: UpdateCredentialAfterLogin :exec
UPDATE credentials
SET sign_count = $2, flag_backup_state = $3
WHERE id = $1
`

type UpdateCredentialAfterLoginParams struct {
	ID              []byte `json:"id"`
	SignCount       int64  `json:"sign_count"`
	FlagBackupState bool   `json:"flag_backup_state"`
}

func (q *Queries) UpdateCredentialAfterLogin(ctx context.Context, arg UpdateCredentialAfterLoginParams) error {
	_, err := q.db.Exec(ctx, updateCredentialAfterLogin, arg.ID, arg.SignCount, arg.FlagBackupState)
	return err
}
