// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: credentials.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCredential = `-- name: CreateCredential :one
INSERT INTO credentials (
    id, user_handle, display_name, public_key, transport,
    sign_count, flag_backup_eligible, flag_backup_state, aaguid,
    last_used_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, NOW())
RETURNING id, user_handle, display_name, public_key, transport, sign_count, flag_backup_eligible, flag_backup_state, aaguid, last_used_at, created_at
`

type CreateCredentialParams struct {
	ID                 []byte      `json:"id"`
	UserHandle         []byte      `json:"user_handle"`
	DisplayName        pgtype.Text `json:"display_name"`
	PublicKey          []byte      `json:"public_key"`
	Transport          []string    `json:"transport"`
	SignCount          int64       `json:"sign_count"`
	FlagBackupEligible bool        `json:"flag_backup_eligible"`
	FlagBackupState    bool        `json:"flag_backup_state"`
	Aaguid             []byte      `json:"aaguid"`
}

func (q *Queries) CreateCredential(ctx context.Context, arg CreateCredentialParams) (Credential, error) {
	row := q.db.QueryRow(ctx, createCredential,
		arg.ID,
		arg.UserHandle,
		arg.DisplayName,
		arg.PublicKey,
		arg.Transport,
		arg.SignCount,
		arg.FlagBackupEligible,
		arg.FlagBackupState,
		arg.Aaguid,
	)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.UserHandle,
		&i.DisplayName,
		&i.PublicKey,
		&i.Transport,
		&i.SignCount,
		&i.FlagBackupEligible,
		&i.FlagBackupState,
		&i.Aaguid,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getCredential = `-- name: GetCredential :one
SELECT id, user_handle, display_name, public_key, transport, sign_count, flag_backup_eligible, flag_backup_state, aaguid, last_used_at, created_at FROM credentials WHERE user_handle = $1
`

func (q *Queries) GetCredential(ctx context.Context, userHandle []byte) (Credential, error) {
	row := q.db.QueryRow(ctx, getCredential, userHandle)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.UserHandle,
		&i.DisplayName,
		&i.PublicKey,
		&i.Transport,
		&i.SignCount,
		&i.FlagBackupEligible,
		&i.FlagBackupState,
		&i.Aaguid,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateCredential = `-- name: UpdateCredential :exec
UPDATE credentials
SET sign_count = $2, flag_backup_state = $3, last_used_at = NOW()
WHERE id = $1
`

type UpdateCredentialParams struct {
	ID              []byte `json:"id"`
	SignCount       int64  `json:"sign_count"`
	FlagBackupState bool   `json:"flag_backup_state"`
}

func (q *Queries) UpdateCredential(ctx context.Context, arg UpdateCredentialParams) error {
	_, err := q.db.Exec(ctx, updateCredential, arg.ID, arg.SignCount, arg.FlagBackupState)
	return err
}
