// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Credential struct {
	ID                 []byte             `json:"id"`
	UserHandle         []byte             `json:"user_handle"`
	DisplayName        pgtype.Text        `json:"display_name"`
	PublicKey          []byte             `json:"public_key"`
	Transport          []string           `json:"transport"`
	SignCount          int64              `json:"sign_count"`
	FlagBackupEligible bool               `json:"flag_backup_eligible"`
	FlagBackupState    bool               `json:"flag_backup_state"`
	Aaguid             []byte             `json:"aaguid"`
	LastUsedAt         pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}
