// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIToken = `-- name: CreateAPIToken :one
INSERT INTO api_tokens (name, token) VALUES ($1, $2) RETURNING id, name, token, last_used_at, created_at
`

type CreateAPITokenParams struct {
	Name  string `json:"name"`
	Token string `json:"token"`
}

func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (ApiToken, error) {
	row := q.db.QueryRow(ctx, createAPIToken, arg.Name, arg.Token)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Token,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAPIToken = `-- name: DeleteAPIToken :exec
DELETE FROM api_tokens WHERE id = $1
`

func (q *Queries) DeleteAPIToken(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAPIToken, id)
	return err
}

const introspectAPIToken = `-- name: IntrospectAPIToken :one
UPDATE api_tokens SET last_used_at = NOW() WHERE token = $1 RETURNING id
`

func (q *Queries) IntrospectAPIToken(ctx context.Context, token string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, introspectAPIToken, token)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const listAPITokens = `-- name: ListAPITokens :many
SELECT id, name, token, last_used_at, created_at FROM api_tokens ORDER BY created_at
`

func (q *Queries) ListAPITokens(ctx context.Context) ([]ApiToken, error) {
	rows, err := q.db.Query(ctx, listAPITokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiToken{}
	for rows.Next() {
		var i ApiToken
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Token,
			&i.LastUsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
