// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (webauthn_id, email)
VALUES ($1, $2)
RETURNING id, webauthn_id, email, created_at
`

type CreateUserParams struct {
	WebauthnID []byte `json:"webauthn_id"`
	Email      string `json:"email"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.WebauthnID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.WebauthnID,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, webauthn_id, email, created_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.WebauthnID,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByWebAuthnID = `-- name: GetUserByWebAuthnID :one
SELECT id, webauthn_id, email, created_at FROM users WHERE webauthn_id = $1
`

func (q *Queries) GetUserByWebAuthnID(ctx context.Context, webauthnID []byte) (User, error) {
	row := q.db.QueryRow(ctx, getUserByWebAuthnID, webauthnID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.WebauthnID,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}
