// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Credential struct {
	ID                 []byte             `json:"id"`
	UserID             pgtype.UUID        `json:"user_id"`
	PublicKey          []byte             `json:"public_key"`
	Transport          []string           `json:"transport"`
	SignCount          int64              `json:"sign_count"`
	FlagBackupEligible bool               `json:"flag_backup_eligible"`
	FlagBackupState    bool               `json:"flag_backup_state"`
	Aaguid             []byte             `json:"aaguid"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID         pgtype.UUID        `json:"id"`
	WebauthnID []byte             `json:"webauthn_id"`
	Email      string             `json:"email"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}
